version: '3'

services:
  app:
    image: gmo_intern:app
    container_name: gmo_intern_app
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  db:
    image: gmo_intern:db
    container_name: gmo_intern_db
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    environment:
      MARIADB_DATABASE: main
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    tty: true